WalletOne/Models/CartIndexViewModel.cs
using WalletOne.Domain.Entities;

namespace WalletOne.Models {
    public class CartIndexViewModel {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

WalletOne/Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WalletOne.Models {
    public class LoginViewModel {
        [Required]
        public string UserName { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

WalletOne/Models/OrderViewModel.cs
using WalletOne.Domain.Entities;

namespace WalletOne.Models
{
    public class OrderViewModel
    {
        public CartIndexViewModel CartIndexViewModel { get; set; }
        public ShippingDetails ShippingDetails { get; set; }
    }
}

WalletOne/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WalletOne.Models {
    public class PagingInfo {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

WalletOne/Models/ProductListViewModel.cs
using System.Collections.Generic;
using WalletOne.Domain.Entities;

namespace WalletOne.Models {
    public class ProductsListViewModel {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

WalletOne/Controllers/AdminController.cs
using WalletOne.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WalletOne.Infrastructure;

namespace WalletOne.Controllers
{
    public class AdminController : Controller {
        public AdminController() {
        }
        public ViewResult Index() {
            return View(DataBaseExplorer.GetProductsFromDataBase(null, 1, DataBaseExplorer.GetTotalCount()));
        }
        public ViewResult Edit(int productId) {
            Product product = DataBaseExplorer.GetProductFromDataBase(productId);
            return View(product);
        }
        [HttpPost]
        public ActionResult Edit(Product product, HttpPostedFileBase image) {
            if (ModelState.IsValid)
            {
                Product prev = DataBaseExplorer.GetProductFromDataBase(product.ProductID);
                if (prev != null) {
                    product.ImageMimeType = prev.ImageMimeType;
                    product.ImageData = prev.ImageData;
                }
                DataBaseExplorer.InsertProduct(product.ProductID == 0, product, image);
                TempData["message"] = string.Format("{0} has been saved", product.Name);
                return RedirectToAction("Index");
            } else {
                return View(product);
            }
        }
        public ViewResult Create() {
            return View("Edit", new Product());
        }
        [HttpPost]
        public ActionResult Delete(int productId) {
            DataBaseExplorer.DeleteProduct(productId);
            return RedirectToAction("Index");
        }
    }
}

WalletOne/Controllers/CartController.cs
using WalletOne.Domain.Entities;
using WalletOne.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WalletOne.HtmlHelpers;
using WalletOne.Infrastructure;

namespace WalletOne.Controllers
{
    public class CartController : Controller
    {
        public CartController() {}
        public ViewResult Index(Cart cart, string returnUrl) {
            return View(new CartIndexViewModel {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = DataBaseExplorer.GetProductFromDataBase(productId);
            if (product != null) {
                cart.AddItem(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToRouteResult TakeFromCart(Cart cart, int productId, string returnUrl) {
            Product product = DataBaseExplorer.GetProductFromDataBase(productId);
            if (product != null) {
                cart.AddItem(product, -1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl) {
            Product product = DataBaseExplorer.GetProductFromDataBase(productId);
            if (product != null) {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public PartialViewResult Summary(Cart cart) {
            return PartialView(cart);
        }
        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails) {
            if (cart.Lines.Count() == 0) {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid) {
                System.Web.HttpContext.Current.Items.Add("Cart", cart);
                System.Web.HttpContext.Current.Items.Add("ShippingDetails", shippingDetails);
                PaymentForm paymentForm = new PaymentForm();
                paymentForm.ProcessRequest(System.Web.HttpContext.Current);
                cart.Clear();
                return View("Completed");
            } else {
                return View(shippingDetails);
            }
        }
        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }
    }
}

WalletOne/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WalletOne.Infrastructure;

namespace WalletOne.Controllers
{
    public class NavController : Controller
    {
        public NavController() {
        }
        public PartialViewResult Menu(string category = null) {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = DataBaseExplorer.GetCategories();
            return PartialView(categories);
        }
    }
}

WalletOne/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WalletOne.Domain.Entities;
using WalletOne.Infrastructure;
using WalletOne.Models;

namespace WalletOne.Controllers {
    public class ProductController : Controller {
        public static int PageSize = 4;

        public ProductController() { }
        public ViewResult List(string category, int page = 1) {
             ProductsListViewModel model = new ProductsListViewModel {
                Products = DataBaseExplorer.GetProductsFromDataBase(category, page, PageSize),
                PagingInfo = new PagingInfo {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = DataBaseExplorer.GetTotalCount(category)
                },
                CurrentCategory = category
            };
            return View(model);
        }
        public FileContentResult GetImage(int productId) {
            Product prod = DataBaseExplorer.GetProductFromDataBase(productId);
            if (prod != null) {
                return File(prod.ImageData, prod.ImageMimeType);
            } else {
                return null;
            }
        }

        
    }
}

WalletOne/Views/Admin/Edit.cshtml
@model WalletOne.Domain.Entities.Product

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit @Model.Name</h1>
@using (Html.BeginForm("Edit", "Admin",
                        FormMethod.Post, new { enctype = "multipart/form-data" })) {
                        @Html.EditorForModel()
                        <div class="editor-label">Image</div>
                        <div class="editor-field">
                            @if (Model.ImageData == null) {
                @:None
                } else {
                <img width="150" height="150" src="@Url.Action("GetImage", "Product", new { Model.ProductID })" />
                }
                            <div>
                                Upload new image:
                                <input type="file" name="Image" />
                            </div>
                        </div>
                        <input type="submit" value="Save" />
                        @Html.ActionLink("Cancel and return to List", "Index")
}

WalletOne/Views/Admin/Index.cshtml
@using System.Globalization
@model IEnumerable<WalletOne.Domain.Entities.Product>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
    <h1>All Products</h1>
    <table class="Grid">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th class="NumericCol">Price</th>
            <th>Actions</th>
        </tr>
        @foreach (var item in Model) {
<tr>
    <td>@item.ProductID</td>
    <td>@Html.ActionLink(item.Name, "Edit", new { item.ProductID })</td>
    <td class="NumericCol">@item.Price.ToString("c", CultureInfo.CreateSpecificCulture("ru-RU"))</td>
    <td>
        @using (Html.BeginForm("Delete", "Admin")) {
@Html.Hidden("ProductID", item.ProductID)
            <input type="submit" value="Delete" />
        }
    </td>
</tr>
        }
    </table>
    <p>@Html.ActionLink("Add a new product", "Create")</p>

WalletOne/Views/Cart/Checkout.cshtml
@model WalletOne.Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "WalletOneStore: Checkout";
}
<h2>Check out now</h2>
Please enter your details, and we'll ship your goods right away!
@using (Html.BeginForm()) {
@Html.ValidationSummary()
    <h3>Ship to</h3>
    <div>Name: @Html.EditorFor(x => x.Name)</div>
    <h3>Address</h3>
    <div>Zip: @Html.EditorFor(x => x.Zip)</div>
    <div>Country: @Html.EditorFor(x => x.Country)</div>
    <div>State: @Html.EditorFor(x => x.State)</div>
    <div>City: @Html.EditorFor(x => x.City)</div>
    <div>Street: @Html.EditorFor(x => x.Address)</div>
    <p align="center">
        <input class="actionButtons" type="submit" value="Complete order"/>
    </p>
}

WalletOne/Views/Cart/Completed.cshtml
@{
    Layout = null;
}

WalletOne/Views/Cart/Index.cshtml
@using System.Globalization
@model WalletOne.Models.CartIndexViewModel

@{
    ViewBag.Title = "WalletOne Store: Your Cart";
}
<h2>Your cart</h2>
<table align="center" width="90%">
    <thead>
        <tr>            
            <th align="left">Item</th>
            <th align="right">Price</th>
            <th align="center">Quantity</th>
            <th align="right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines) {
<tr>
    <td align="left">@line.Product.Name</td>
    <td align="right">@line.Product.Price.ToString("c", CultureInfo.CreateSpecificCulture("ru-RU"))</td>
    <td align="center">
        <table>
            <tr>
                <td>
                    @using (Html.BeginForm("TakeFromCart", "Cart")) {
                    @Html.Hidden("ProductId", line.Product.ProductID)
                        @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                        <input class="actionButtons" type="submit" value="-" style="padding: .15em 0.55em .2em 0.5em;" />
                    }
                </td>
                <td>
                    @line.Quantity
                </td>
                <td>
                    @using (Html.BeginForm("AddToCart", "Cart")) {
                    @Html.Hidden("ProductId", line.Product.ProductID)
                        @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                        <input class="actionButtons" type="submit" value="+" style="padding: .15em 0.55em .2em 0.5em;" />
                    }
                </td>
            </tr>

        </table>
    </td>

    <td align="right">@((line.Quantity * line.Product.Price).ToString("c", CultureInfo.CreateSpecificCulture("ru-RU")))</td>
    <td>
        @using (Html.BeginForm("RemoveFromCart", "Cart")) {
            @Html.Hidden("ProductId", line.Product.ProductID)
            @Html.HiddenFor(x => x.ReturnUrl)
            <input class="actionButtons" type="submit" value="Remove" />
        }
    </td>
</tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" align="right">Total:</td>
            <td align="right">
                @Model.Cart.ComputeTotalValue().ToString("c", CultureInfo.CreateSpecificCulture("ru-RU"))
            </td>
        </tr>
    </tfoot>
</table>
<p align="center" class="actionButtons">
    <a href="@Model.ReturnUrl">Continue shopping</a>
    @Html.ActionLink("Checkout now", "Checkout")
</p>

WalletOne/Views/Cart/Summary.cshtml
@using System.Globalization
@model WalletOne.Domain.Entities.Cart

<div id="cart">
    <span class="caption">
        <b>Your cart:</b>
        @Model.Lines.Sum(x => x.Quantity) item(s),
        @Model.ComputeTotalValue().ToString("c", CultureInfo.CreateSpecificCulture("ru-RU"))
    </span>
    @Html.ActionLink("Checkout", "Index", "Cart", new {
    returnUrl =
Request.Url.PathAndQuery
}, null)
</div>

WalletOne/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Home", "List", "Product")

@foreach (var link in Model) {
@Html.RouteLink(link, new {
    controller = "Product",
    action = "List",
    category = link,
    page = 1
},
new {
    @class = link == ViewBag.SelectedCategory ? "selected" : null
})
}

WalletOne/Views/Product/List.cshtml
@model WalletOne.Models.ProductsListViewModel

@{
    ViewBag.Title = "Products";
}

@foreach (var p in Model.Products) {
    Html.RenderPartial("ProductSummary", p);
}

<div class="pager">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new { page = x, category = Model.CurrentCategory }))
</div>

WalletOne/Views/Shared/ProductSummary.cshtml
@using System.Globalization
@model WalletOne.Domain.Entities.Product

<div class="item">
    @if (Model.ImageData != null) {
<div style="float: left; margin-right: 20px">
    <img width="75" height="75" src="@Url.Action("GetImage", "Product", new { Model.ProductID })" />
</div>
    }
    <h3>@Model.Name</h3>
    @Model.Description
    <div class="inneritem">
        @using (Html.BeginForm("AddToCart", "Cart")) { 
            @Html.HiddenFor(x => x.ProductID) 
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" value="+ Add to cart" />
        }
    </div>
    <h4>@Model.Price.ToString("c", CultureInfo.CreateSpecificCulture("ru-RU"))</h4>
</div>

WalletOne/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/Admin.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-1.7.1.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @if (TempData["message"] != null) {
        <div class="Message">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

WalletOne/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Site.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <div id="header">
        @{Html.RenderAction("Summary", "Cart");}
        <div class="title">Wallet One STORE</div>
    </div>
    <div id="categories">
        @{ Html.RenderAction("Menu", "Nav"); }
    </div>
    <div id="content">
        @RenderBody()
    </div>
</body>
</html>

WalletOne/Views/View.cshtml
@model IEnumerable<WalletOne.Domain.Entities.Product>

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ProductID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ProductID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ProductID })
        </td>
    </tr>
}

</table>